# Generated by Django 2.2.7 on 2020-08-27 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200827_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=128, verbose_name='языки'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_profile_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='языки'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 15, 13, 52, 133747, tzinfo=utc)),
        ),
    ]
