# Generated by Django 2.2.7 on 2020-08-31 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200827_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 8, 32, 37, 746884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=512, verbose_name='языки'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='vk_profile_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на профиль'),
        ),
    ]
